baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir = 'false'
[languages]
  [languages.en]
    languageName = 'English'
    languageCode = 'en'
    title = 'In English'
    weight = 100
  [languages.de]
    languageName = 'Deutsch'
    languageCode = 'de-DE'
    title = 'En Deutsch'
    weight = 200
  [languages.ru]
    languageName = 'Русский'
    languageCode = 'ru'
    title = 'En Русский'
    weight = 300
